### ISSUE TITLE
some exceptions

### ISSUE THREAD

**Issue by imouhero** [T0shik/aspnetcore3-authentication#1]
I'll follow your instructional video and type the code. In the Ep.6 OAuth Client video, after I wrote the Token method, I tried to run it and type bob and got the following exceptions:

IOException: The response ended prematurely.
System.Net.Http.HttpConnection.FillAsync()

HttpRequestException: Error while copying content to a stream.
System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)

Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()

I did not find the solution online.

**Comment by drazen64** [comment]
I got the same exception.
A workaround I found is to change Token() action definition from:
`public async Task<IActionResult> Token(`
to:
`public async Task Token(...`
and to remove `return` from the last line: 
`Redirect(redirect_uri);`

I'm not sure what's going on (seems like  `return` fires before `WriteAsync` finishes), but the above solution seems to help.
Behaviour is the same for both .net core 3.0 and 3.1

**Comment by zpc870921** [comment]
I got the same exception

**Comment by kateract** [comment]
@drazen64 Are you awating the WriteAsync call then?  I did not get the same errors with 3.1.

**Comment by drazen64** [comment]
> @drazen64 Are you awating the WriteAsync call then? I did not get the same errors with 3.1.
Yes, there is await. The code is checked out of this repository. 

If you check youtube comments, it seems that the problem might be in a webserver.  These errors happen only if you use VS Code, but not if you use VS.
VS Code works with Kestrel, while (if I remember correctly) VS uses IIS in combination with Kestrel.

**Comment by T0shik** [comment]
Sorry for letting this issue hang, didn't expect to get people commenting on the repo.

As @drazen64 said, main error seemed to be happening when running on Kestrel. Issue didn't seem to happen on ISS Express.

Quick fix is, replace: 
```
var responseJson = JsonConvert.SerializeObject(responseObject);
var responseBytes = Encoding.UTF8.GetBytes(responseJson);
await Response.Body.WriteAsync(responseBytes, 0, responseBytes.Length);
return  Redirect(redirect_uri);
```
with `return responseObject` and don't forget to change return type of the function to `public object Token(...`

**Please remember that the OAuth arch is meant to explain the flow of tokens it's not a production ready implementation**

**Comment by jducobu** [comment]
What to do to use this architecture in production ?

**Comment by jducobu** [comment]
> Sorry for letting this issue hang, didn't expect to get people commenting on the repo.
> 
> As @drazen64 said, main error seemed to be happening when running on Kestrel. Issue didn't seem to happen on ISS Express.
> 
> Quick fix is, replace:
> 
> ```
> var responseJson = JsonConvert.SerializeObject(responseObject);
> var responseBytes = Encoding.UTF8.GetBytes(responseJson);
> await Response.Body.WriteAsync(responseBytes, 0, responseBytes.Length);
> return  Redirect(redirect_uri);
> ```
> 
> with `return responseObject` and don't forget to change return type of the function to `public object Token(...`
> 
> **Please remember that the OAuth arch is meant to explain the flow of tokens it's not a production ready implementation**
What to do to use this arch in production ?
