### ISSUE TITLE
Authentication and Authorization Inquire

### ISSUE THREAD

**Issue by Mr-alaa** [T0shik/aspnetcore3-authentication#5]
Many thanks for your videos and project I have followed your videos everything is clear  and i have used this tutorial in my login with SQL server  like this 

` [HttpPost]
        public async Task<IActionResult> Login(string username, string password)
        {
            var user = await _userManager.FindByNameAsync(username);

            if (user != null)
            {
              var signResult = await  _signInManager.PasswordSignInAsync(user, password, false, false);

              if (signResult.Succeeded)
              {
                    // return RedirectToAction("index");

                    var grandmaClaims = new List<Claim>()
                    {
                        new Claim(ClaimTypes.Name, username),
                        new Claim(ClaimTypes.Email, "Bob@fmail.com"),
                        new Claim(ClaimTypes.DateOfBirth, "11/11/2000"),
                        new Claim(ClaimTypes.Role, "Admin"),
                        new Claim(ClaimTypes.Role, "AdminTwo"),
                        new Claim(DynamicPolicies.SecurityLevel, "7"),
                        new Claim("Grandma.Says", "Very nice boi."),
                    };

                    var licenseClaims = new List<Claim>()
                    {
                        new Claim(ClaimTypes.Name, "Bob K Foo"),
                        new Claim("DrivingLicense", "A+"),
                    };

                    var grandmaIdentity = new ClaimsIdentity(grandmaClaims, "Grandma Identity");
                    var licenseIdentity = new ClaimsIdentity(licenseClaims, "Government");

                    var userPrincipal = new ClaimsPrincipal(new[] { grandmaIdentity, licenseIdentity });
                    //-----------------------------------------------------------

                    HttpContext.SignInAsync(userPrincipal);

                    return RedirectToAction("Index");

              }

            }

            return RedirectToAction("index");
        }`

my question is using claims looks like the same jwt and is enough to use and also I can't find customized claims fields in claims like new Claim("Grandma.Says", "Very nice boi."), how and catch it to get data my last question is in browser cookies I have git different name in startup cookie name is `   config.Cookie.Name = "Grandmas.Cookie";`

but in the browser is 

![image](https://user-images.githubusercontent.com/20131615/82156541-d75fca80-987b-11ea-80a3-5e7da09a73ef.png)

**Comment by T0shik** [comment]
Your cookie in the browser is encrypted.

You would get your claims form the `HttpContext` before you render the page like so `HttpContext.User.Claims...` and then use Linq or whatever to grab the values.

**Comment by Mr-alaa** [comment]
many thanks for the response but I make debugger to watch the data there i didn't see the customize one like   new Claim("Grandma.Says", "Very nice boi."), only user name and arm or Role
and when git AccessDenied  it redirect me to 
https://localhost:44358/Account/AccessDenied?ReturnUrl=%2FHome%2FSecretRole

despite it in start up as you shown before 
 
  services.AddAuthentication("CookieAuth")
                .AddCookie("CookieAuth", config =>
                {
                    config.Cookie.Name = "Grandmas.Cookie";
                    config.LoginPath = "/Home/Authenticate";
                });

**Comment by Mr-alaa** [comment]
only theses claims are there despite through videos it is declared there 

   var grandmaClaims = new List<Claim>()
                {
                    new Claim(ClaimTypes.Name, username),
                    new Claim(ClaimTypes.Email, "Bob@fmail.com"),
                    new Claim(ClaimTypes.DateOfBirth, "11/11/2000"),
                    new Claim(ClaimTypes.Role, "Admin"),
                    new Claim(ClaimTypes.Role, "AdminTwo"),
                    new Claim(DynamicPolicies.SecurityLevel, "7"),
                    new Claim("Grandma.Says", "Very nice boi."),
                };

![image](https://user-images.githubusercontent.com/20131615/82234100-359ab500-9931-11ea-88a1-3acf0062cf2e.png)

**Comment by T0shik** [comment]
how did you sign in?
